# Generated by Django 4.0.3 on 2022-04-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skpi_management_app', '0023_alter_konfirmasidata_mahasiswa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konfirmasidata',
            name='setuju',
            field=models.BooleanField(default=False, help_text='Klik'),
        ),
    ]
